#! /bin/bash

if [ $# != 4 ]
then
  echo Help : argfile_name, nb_input, nb_middle, nb_output
fi

echo \#Autogen by gnagnagnagna > $1
echo >> $1
echo "NEURONS - NAME : TYPE, LAYER" >> $1
for i in $(seq 1 $2)
do
  echo input$i : SIGMOID, 0 >> $1
done

for i in $(seq 1 $3)
do
  echo middle$i : SIGMOID, 1 >> $1
done

for i in $(seq 1 $4)
do
  echo output$i : SIGMOID, 2 >> $1
done

echo >> $1
echo BACKWARD_LINKS - NAME : PARENTS\' NAMES >> $1

for i in $(seq 1 $3)
do
  printf "middle$i : " >> $1
  for j in $(seq 1 $(echo $2-1 | bc))
  do
    printf "input$j, " >> $1
  done
  printf "input$2\n" >> $1
done


for i in $(seq 1 $4)
do
  printf "output$i : " >> $1
  for j in $(seq 1 $(echo $3-1 | bc))
  do
    printf "middle$j, " >> $1
  done
  printf "middle$3\n" >> $1
done

echo >> $1
